//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Lab_phase3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public int ModelID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public Nullable<int> TypeID { get; set; }
    
        public virtual Car_Type Car_Type { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
