//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Lab_phase3
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppliersDetail
    {
        public string CustomerFullName { get; set; }
        public string Gender { get; set; }
        public string NationalCode { get; set; }
        public string EmailAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
    }
}
