//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Lab_phase3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public System.Guid VIN { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> Milage { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public string Fuel { get; set; }
    
        public virtual Car_Type Car_Type { get; set; }
        public virtual Color Color { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
